### PR TITLE
change url to node

### PR DESCRIPTION
**Pull request by ewingson**
I have made the smallest possible change.
is [L127](https://github.com/SolidOS/solid-logic/blob/2bf19bb6d55c0ccb2cccc37b0a62662ecfb3e977/src/util/UtilityLogic.ts#L127) okay ? (occurance of containerUrl)
I have used [vscode.dev](https://vscode.dev/) and followed "goto Definition".
what else needs to be done ? (occurances of variables that need to be replaced)
please understand this is my first PR of actual Solid Code since late [2018](https://github.com/ewingson?tab=overview&from=2018-12-01&to=2018-12-31).
don't know how to request review in github.
we do teamwork...

### CODE REVIEW

**Comment by ewingson** [comment]
old (Promise string was passed)
new (NamedNode is passed, maybe introduce Promise in ff line)

I was not sure, if we completely can leave out Line 127.
somewhere the construction of the Promise must be introduced.
still get used to it (coming from procedural).
please review and stay patient.

**Comment by ewingson** [comment]
materialized it out with @timea-solid .
why do the checks fail ?
what next ?

**Comment by ewingson** [comment]
changed L137 (call of the changes function)
am not sure if `containerNode` is there already in the scope...

**Comment by ewingson** [comment]
I'm only ninetyeight point something sure about this

**Comment by ewingson** [comment]
url => containerNode

**Comment by ewingson** [comment]
fixed one error.
another one popped up.

**Comment by ewingson** [comment]
advancing slowly.
changing `any` to `NamedNode`.
need review, if I am on the right path, @timea-solid

**Comment by timea-solid** [comment]
Well done so far!
I made comments on the lines of code. 
You have completed the  and changed recursiveDelete function which was using

**Comment by ewingson** [comment]
reverted to `any` in two files...

**Comment by ewingson** [comment]
from 11/12 errors to 2/11 errors - progress...

**Comment by ewingson** [comment]
now I have a strange effect:

I have done 1. https://github.com/SolidOS/solid-logic/pull/38/commits/8e8d9661dae105b58ef5638eb644fee7d2ff8fb4 2. revert https://github.com/SolidOS/solid-logic/pull/38/commits/10ccdd3e88e0bbdac0d00ae072e273cdf09b98bd

and the builld run shows different results

1. https://github.com/SolidOS/solid-logic/actions/runs/2242340555
2. https://github.com/SolidOS/solid-logic/actions/runs/2242381396

**Comment by ewingson** [comment]
a) a heap of internal errors - fetcher issue
b) inbox - array prob
c) `containerNode.doc()` is not a function

**Comment by timea-solid** [comment]
Your investigation and actions are correct!
To have an easier time to get to the problems you can locally, on your code run `npm run test`. I believe it might give you better error messages than what you see here in git. 
So please try `npm run test`.

**Comment by ewingson** [comment]
@timea-solid

I omitted the 4th parameter, which is the document itself and I thought won't be necessary.
`npm run test` showed progress, only 2 errors instead of 4.
now 
a) the package json and the package lock json was modified cause I needed to install jest locally.
b) the utilityLogic.test.ts now throws the following
```
Utility logic › getContainerMembers › When container has some containment triples › Resolves to an array with some URLs

    expect(received).toEqual(expected) // deep equality

    - Expected  - 4
    + Received  + 1

    - Array [
    -   "https://container.com/bar/",
    -   "https://container.com/foo.txt",
    - ]
    + Array []

      56 |       });
      57 |       it("Resolves to an array with some URLs", () => {
    > 58 |         expect(result.sort()).toEqual([
         |                               ^
      59 |           'https://container.com/foo.txt',
      60 |           'https://container.com/bar/'
      61 |         ].sort());

      at Object.<anonymous> (test/utilityLogic.test.ts:58:31)
```
I don't know, how to proceed, cause it's in another file now and the test *should* work, shouldn't it ?
but overall I slowly gain debug security in touching the code ;-)

ideas ?

**Comment by timea-solid** [comment]
I checked your code locally. 
The 2 test fails you see are because of the use of the .getContainerMembers function. For example in in the line of code in the InboxLogic: https://github.com/ewingson/solid-logic/blob/c2225db9d0a1f1253cb67372d125b3a61d9d5693/src/inbox/InboxLogic.ts#L29 -> there is a problem there see screenshot:
grafik
It has to do with exactly what you changed, string to NamedNode. 
You need to find all functions that make use of getContainerMembers  and make sure to pass a NamedNode and NOT a string anymore. 
hope this helps 🤗

**Comment by ewingson** [comment]
I think the test tests    L139 return nodes.map(node => node.value);

and receives other than expected. Now I gonna *understand*  that ...

**Comment by timea-solid** [comment]
Yes, looks good to me. Try to understand return nodes.map(node => node.value); and fix it.
Unfortunately, there will be more lines coming your way. Do not get discouraged. You are on the right path.
You can also run npm run build and you will see what issues are left to solve.

**Comment by ewingson** [comment]
fixed another one, @timea-solid !
5 left ...

**Comment by ewingson** [comment]
caught another one, @timea-solid !
4 left ...

**Comment by ewingson** [comment]
3 ...

**Comment by ewingson** [comment]
@timea-solid 

I have changed the fetch type:
L16 `constructor(store: LiveStore, ns: SolidNamespace, underlyingFetch: { fetch: (url: NamedNode, options?: any) => any }) {`

now the errors have increased again.
would like to synch with you, if I'm still on the right path...

**Comment by timea-solid** [comment]
> @timea-solid
> 
> I have changed the fetch type: L16 `constructor(store: LiveStore, ns: SolidNamespace, underlyingFetch: { fetch: (url: NamedNode, options?: any) => any }) {`
> 
> now the errors have increased again. would like to synch with you, if I'm still on the right path...

The Fetcher should not be changed. So you need to revert your code and find a way to use string from namedNode here.

**Comment by ewingson** [comment]
reverted to pre-fetch-changes.
3 errors left.

**Comment by ewingson** [comment]
UtilityLogic.ts L 97-101
```
async createContainer(url: string) {
    const stringToNode = url._what_here_?()
    if (!this.isContainer(stringToNode)) {
      throw new Error(`Not a container URL ${url}`);
    }
```
I need to do just the opposite of what you did in the function above this snippet.
createContainer seems to stay passed a string, cause the fetch requires it.

so, how do I convert a string to a named node ? I think in the direction of first declare a new named node......

**Comment by ewingson** [comment]
solved it like this
```
async createContainer(url: string) {
    const stringToNode = new NamedNode (url);
    if (!this.isContainer(stringToNode)) {
      throw new Error(`Not a container URL ${url}`);
    }
```
2 left

**Comment by ewingson** [comment]
fixed another one.
only one left.
```
src/util/UtilityLogic.ts:146:41 - error TS2552: Cannot find name 'url'. Did you mean 'URL'?

146       return this.underlyingFetch.fetch(url, { method: "DELETE" });
                                            ~~~

  node_modules/typescript/lib/lib.dom.d.ts:14005:13
    14005 declare var URL: {
                      ~~~
    'URL' is declared here.


Found 1 error in src/util/UtilityLogic.ts
```
not sure how to proceed...

**Comment by ewingson** [comment]
yippie !!!

**Comment by timea-solid** [comment]
> solved it like this
> 
> ```
> async createContainer(url: string) {
>     const stringToNode = new NamedNode (url);
>     if (!this.isContainer(stringToNode)) {
>       throw new Error(`Not a container URL ${url}`);
>     }
> ```
> 
> 2 left

This fix is breaking some tests. So it is not correct just yet.

**Comment by timea-solid** [comment]
Ok I looked at the code and there are some things I needed to check and also learn. 
1. What is a NamedNode -> https://linkeddata.github.io/rdflib.js/doc/classes/NamedNode.html
2. From the [test fails](https://github.com/SolidOS/solid-logic/runs/6561924582?check_suite_focus=true#step:6:210) we can see a NamedNode looks like:
```
 NamedNode {
    "classOrder": 5,
   "termType": "NamedNode",
    "value": "https://container.com/bar/",
    },
    ```
    This means the code at [L93](https://github.com/ewingson/solid-logic/blob/6feb1cef67833fd36d35ae685b45607b11d01dc0/src/util/UtilityLogic.ts#L93) is not correct. 
    
 So what can we use instead of url.toString() ? from the NamedNode functions?

**Comment by ewingson** [comment]
I tried `String(url.value)` but this was not the final solution.
maybe another step in the right direction ?
can you teach me how to read the test results (how did you find L93 is the problem?)

**Comment by ewingson** [comment]
I've modified a bit and tried the named node method value
```
isContainer(url: NamedNode) {
    const nodeToString = url.value;
    return nodeToString.charAt(nodeToString.length-1) === "/";
  }
```
negative.

**Comment by ewingson** [comment]
tried `url uri()` , `url.uri` and `url.doc()` . negative.
I reverted to `url.value` cause that way at least the `npm run build` passes.

**Comment by timea-solid** [comment]
Tests should be fixes now. It made sense to fix them since we needed to propagate in tests the fact that we use NamedNodes and not strings.

**Comment by ewingson** [comment]
@timea-solid superb !

what is https://github.com/SolidOS/solid-logic/runs/6964470253?check_suite_focus=true ?

this whole CI deploy workflow still is a land with hidden doors to me ;-(

**Comment by timea-solid** [comment]
> @timea-solid superb !
> 
> what is https://github.com/SolidOS/solid-logic/runs/6964470253?check_suite_focus=true ?
> 
> this whole CI deploy workflow still is a land with hidden doors to me ;-(

You can ignore the npm publish. That step should upload the artifact to npm which because we are on a dev branch it can be ignored. It would only be needed if you further need this dev artifact to integrate into another and develop cross modules (which is something I do often).

**Comment by ewingson** [comment]
@timea-solid 

I'm working myself "back-to-forth". I hit two other variables, that need to be NamedNode, otherwise the function in question is not callable. it's `ourInbox` and `options.target`

**Comment by ewingson** [comment]
@timea-solid a good scientist communicates in the openness and peer review is a commonly wide accepted method.

my `npm run build` locally only shows one remaining error.
I have converted `options.target` to a NamedNode.
I wanted to synch with you the further processing.

a) can I try to convert `ourInbox`to a node, too ? I would need to import `sym` therefor to `InboxLogic.ts` .....
b) my first and mostdesired aim is to make npm run build without errors.
then, in a second step, we can care about the CI build. momentary it complains about that it wants absolute URIs.

what do you think ? my main work happens between 17 and 00 o'clock.
there are more things (an ocean) that I do NOT know opposed to a drop I understood ;-)

**Comment by timea-solid** [comment]
I htink 'ourInbox' should stay a string for 'createContainer' call but for 'this.util.findAclDocUrl(ourInbox)' is should be a NamedNode. 
Also 'this.util.setSinglePeerAccess' could do some change on 'ownerWebId', 'peerWebId'.
Also in the 'markAsRead' url can be changed.

**Comment by ewingson** [comment]
shall I PR to resolve conflicts ?

**Comment by ewingson** [comment]
@timea-solid !!!!!

I solved that merge thang ! so I understood more than *nothing* !
hope that helps !

**Comment by ewingson** [comment]
changed as in https://github.com/SolidOS/solid-logic/pull/38#issuecomment-1161354841

**Comment by ewingson** [comment]
@timea-solid 

`npm run build` throws no more errors. that's progress.
can you help me interpret the CI tests as follows:
```
Test Suites: 2 failed, 7 passed, 9 total
Tests:       3 failed, 2 skipped, 64 passed, 69 total
Snapshots:   0 total
Time:        6.561 s
Ran all test suites.
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```
I'll wrap my head upon jest a while, as suggested.
maybe @SharonStrats can help.

can we jump on a call during this week ?

**Comment by ewingson** [comment]
obsolete because of https://github.com/SolidOS/solid-logic/pull/45

**Pull request closed without merging**
