### PR TITLE
Discovery

### PR DESCRIPTION
**Pull request by timea-solid**
Refactoring of new discovery code.
List of changes:
-> swithced from object oriented to functional with dependency injection and higher order functions.
-> no more use of an extra caching because rdflib already takes care of that
-> discoveryLogic has been split up to typeIndexLogic, profileLogic and utilityLogic
* deleted:
- ensureTypeIndex
- loadTypeIndex
- ensureOneTypeIndex (used putindex and makeIndesIfNecessary)
- loadIndex
- loadIndexes
- getTypeIndex
- ensureLoadedPreferences,
* changes in parameters
- registerInTypeIndex
* changes only in the code of a function
- loadPreferences
-loadProfile

### CODE REVIEW

**Comment by timea-solid** [comment]
implemented feedback after pair programming with Angelo.

**Review by angelo-v — APPROVED** [review]
Timea and I have discussed the higher-order-function approach with dependency injection on Gitter and did a bit of pairing on the topic. From my side it is ready to merge, provided manual testing does not reveal any issues

**Comment by timea-solid** [comment]
Please make a new major version of this solid-logic upon release. This major release will also include the change from strings to NamedNode but that merge is still open, will be done soon.

**Comment by timea-solid** [comment]
Identified 2 bugs:
* for the preference file creation when we have none: it creates the settings container with a capital 'S' but most of our Pods have a container 'settings' with lower letters which has typeIndexes and so. Exact line is: [L36 of utils](https://github.com/SolidOS/solid-logic/blob/af110ecf08466c3a434ec4ef8e395a7414c65350/src/util/utils.ts#L36). Not sure what the resolution should be.
* for the publicTypeIndex file creation when we have none: the code returns a 404 `fetchFactory.js:35          GET https://timeatest.solidcommunity.net:8443/profile/publicTypeIndex.ttl 404 (Not Found)` which theoretically should already be solved on [L35 of utilityLogic](https://github.com/SolidOS/solid-logic/blob/af110ecf08466c3a434ec4ef8e395a7414c65350/src/util/utilityLogic.ts#L35) however something is wrong and it is not taken into consideration.

In both bugs the way I tested:
1. Log into test server https://timeatest.solidcommunity.net:8443/profile/card#me
2. Go to my profile card in storage
3.a. delete the line `space:preferencesFile </settings/prefs.ttl>;`for testing missing preference file
3.b. delete line 'solid:publicTypeIndex </settings/publicTypeIndex.ttl>; for testing missing PUBLIC typeIndex
Remark: for publicTypeIndex -> the new triple was added to the profile card but is missing 'settings'. Not sure if this is ok.

**Comment by timbl** [comment]
See thread in response to https://gitter.im/solid/solidos?at=62d913558fe56a38b5b1f043 about `Settings` vs `settings`.

Why would you migrate the data? It at the end of the day an open choice by user, or mostly by app library writer, how to name the preferences file.

If different versions of the OS have ended up giving people different names for them, that’s OK as you always follow the links not assume the name!

[Jul 21 16:40](https://gitter.im/solid/solidos?at=62d9b9d3904f20479a2213a3)
I personally prefer capitalized full nounds.

Tim Berners-Lee
@timbl
[Jul 21 16:47](https://gitter.im/solid/solidos?at=62d9bb49ab6b634f7362a481)
When Steve Jobs took a unix system full of awk, grep /var/lib and tried to make it user frendly as the NeXT, he made the names readable like /Library and Documents not lib and docs. That got taken on the OSX for the Mac. Windows also uses long capitalized names. I think having user-legible names is important for Solid pods too. We should adopt that policy in SolidOS when we pick default names.

**Comment by jeff-zucker** [comment]
So - write "Settings"; read whatever is pointed to with the expected predicates;  don't mention names or paths in the spec?

**Comment by timea-solid** [comment]
Dedicated ticket still open for the typeIndex 404 problem https://github.com/SolidOS/solid-logic/issues/47

**Pull request merged**
